services:
  web:
    env_file:
      - docker.env

    build:
      context: .

    command: bash -c "yarn test"

    volumes:
      # make sure these line up with $APP_DIR
      - node_modules:${APP_DIR}/node_modules
      - .:${APP_DIR}

    ports:
      - "4000:4000"
      - "8080:8080"

volumes:
  node_modules:
